### ISSUE TITLE
API notes for clm variable

### ISSUE THREAD

**Issue by kiwibrew** [Cloud-RF/CloudRF-API-clients#20]
In the Swagger API docs here: https://cloudrf.com/documentation/developer/swagger-ui/ the clm variable is shown to take $int32 with a minimum of 1 and a maximum of 2.

The accompanying notes say: "Custom clutter: 0=Disabled; 1=Enabled"

Please update the accompanying notes to reflect the requirements of the API.

![Screen Shot 2022-07-26 at 12 22 03 PM](https://user-images.githubusercontent.com/3412790/180896979-5e1099e8-d4ae-42c9-8fbc-17a296977dcc.png)

**Comment by AlexWinder** [comment]
Hi @kiwibrew!

Thanks for bringing this to our attention. We have since fixed this and is due for a release later this week.

For your records we have updated this section to the following:

![image](https://user-images.githubusercontent.com/24867605/181228599-42ed03b9-3817-433f-8ebc-5ab53df4eb1f.png)

**Comment by AlexWinder** [comment]
Hi @kiwibrew 

Sorry for the delay - we have recently taken the opportunity to update all of the documentation and have pushed up an update on the live system for both the ReadTheDocs and on the Swagger UI. These changes have brought the documentation in line with the current versions of systems.

Please note that your Swagger UI may be cached with the previous version. In which case you have a few options available to display the latest version:

- Empty the cache for your browser.
- Visit the web page in an Incognito browser.
- At the top of the Swagger UI page where it is loading in the `Cloud-RF_API2.0.yaml` you can append a nonce to force your browser to grab the latest version, for example `Cloud-RF_API2.0.yaml?foo=bar`.

If you find any further issues then please don't hesitate to let us know.

Alex
