### ISSUE TITLE
URL CloudRF.ini

### ISSUE THREAD

**Issue by SifalB** [Cloud-RF/CloudRF-API-clients#21]
Hi Everyone,

Beware in the cloudRF.ini the url has changed.

It is not : base_url = https://api.cloudrf.com/V2
but : base_url = https://api.cloudrf.com

Regards

**Comment by FarrantAlex** [comment]
Thanks for highlighting this. /v2 is still valid for versioning but in the next version it will be shortened to https://api.cloudrf.com now that /v1 is deprecated.
