### ISSUE TITLE
Checking the progress of a CloudRF API calculation

### ISSUE THREAD

**Issue by fixmaker** [Cloud-RF/CloudRF-API-clients#22]
Currently if we use the API (e.g. `https://api.cloudrf.com/v2/area`) to generate a heatmap, then the network call will block until the calculation is complete. For calculations of long duration it's difficult to know whether the calculation is still running, and how long until it completes.

Is there a way to query the progress of a currently running calculation that was triggered via the API?

**Comment by FarrantAlex** [comment]
There is a private API the interface uses to create the progress bar. Just add your UID and call this every second:
https://api.cloudrf.com/API/progress.php?uid=1

**Comment by fixmaker** [comment]
> There is a private API the interface uses to create the progress bar. Just add your UID and call this every second: https://api.cloudrf.com/API/progress.php?uid=1

Thanks for the info @FarrantAlex . One question: what will happen to this progress indicator if two concurrent calls (to generate different heatmaps in parallel) are made to the API?

**Comment by FarrantAlex** [comment]
Why would you run heatmaps in parallel when that's against our ToS?
https://cloudrf.com/terms-and-conditions/
See 5.3.1

You would need more than one account if you want to do this - which would also answer the progress bar question.
