### ISSUE TITLE
Existing Template Download

### ISSUE THREAD

**Issue by MCRF418** [Cloud-RF/CloudRF-API-clients#35]
Existing templates on the CloudRF UI are not downloading into the ATAK plugin.

This has been tested using ATAK 5.1.0.CIV and Soothsayer 1.3.3

**Comment by Tissy** [comment]
This above was originally reported by me.

Having removed two of the existing and redundant templates, it does try to sync, however I am now seeing this error on the template I am trying to import and therefore it is failing to load.

`java.lang.NumberFormatException: For input string: "0,90,180,270"`

Perhaps a parsing issue on this JSON which I can send over if required.

Many thanks.

**Comment by FarrantAlex** [comment]
Fixed in 1.3.4:
https://github.com/Cloud-RF/SOOTHSAYER-ATAK-plugin/releases/tag/1.3.4
