### ISSUE TITLE
'clh' column should be 'cll' in API examples

### ISSUE THREAD

**Issue by ringhilterra** [Cloud-RF/CloudRF-API-clients#5]
For example here: https://github.com/Cloud-RF/CloudRF-API-clients/blob/master/python/python3.X/area.csv

Based on https://api.cloudrf.com/ documentation there is no 'clh' parameter, I believe it is meant to be 'cll'

**Comment by Cloud-RF** [comment]
The example is out of date but it is not meant to be cll.
clh was an obsolete parameter related to a random clutter height. 
The updated example will include 'cll' and it's accompanying parameter 'mat' so you can model soft clutter with an attenuation of 0.1 dB/m as: cll=2, mat=0.1
 
Thanks.

**Comment by Cloud-RF** [comment]
Fixed with new examples.
